Александр  Рогов
urfu-2017/webdev-task-3 pull request #21
Opened 2018-03-22 11:41 UTC by San4eyZ

2018-03-22 11:41 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-06 20:34 UTC, evgenymarkov requested changes

2018-04-06 20:34 UTC, evgenymarkov commented on package.json
> +    "node-fetch": "2.1.1"
Зачем тебе 'node-fetch'? Ты его нигде не используешь. Он нужен для того чтобы получить fetch-подобный API в NodeJS. Кстати, в поведении fetch на сервере и клиенте есть отличия. Если интересно, можешь почитать [здесь](https://github.com/bitinn/node-fetch/blob/master/LIMITS.md).

2018-04-06 20:34 UTC, evgenymarkov commented on public/media/cancel.svg
> +<svg width="24" height="24" xmlns="http://www.w3.org/2000/svg">
Давай оптимизируем SVG. Лучше всего воспользоваться утилитой `svgo`. 
![2018-04-06_17-54-33](https://user-images.githubusercontent.com/16443248/38422284-95857ce0-39c3-11e8-88d5-e43a1f825a70.png)

2018-04-06 20:34 UTC, evgenymarkov commented on public/index.css
> +.app {
Результаты компиляции пушить вместе с исходным кодом не принято

2018-04-06 20:34 UTC, evgenymarkov commented on public/index.less
> +@main-color: #2ea4ed;
Обсудили в телеграмме "За" и "Против" использования Less. Придираться не буду.

2018-04-06 20:34 UTC, evgenymarkov commented on public/index.html
> +                        <svg viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg">
Чистый и опрятный HTML и тут такое) Давай вынесем в `img src` или с помощью `background-image`. Иконку было бы неплохо отцентрировать по вертикали вместе с "Места".

2018-04-06 20:34 UTC, evgenymarkov commented on public/index.html
> +        <form class="create">
Не лучшее название класса для формы

2018-04-06 20:34 UTC, evgenymarkov commented on public/index.html
> +        <span class="footer__copy">&copy; kvas</span>
Если что это Кузнецов Василий (kvas) и можно свой копирайт оставить))

2018-04-06 20:34 UTC, evgenymarkov commented on public/index.less
> +            fill: #f00;
А вёрстку ты конечно проверял только в Chrome)
Добро пожаловать в реальный мир, не работает hover в Firefox

2018-04-06 20:34 UTC, evgenymarkov commented on public/index.js
> +    filterRadios.forEach(radio => radio.addEventListener('change', filter));
Это плохая практика навешивать eventListener на каждый элемент в группе. Разобраться можно [здесь](https://learn.javascript.ru/event-delegation).

2018-04-06 20:34 UTC, evgenymarkov commented on public/index.js
> +        placeContainer.draggable = true;
Не работает в Firefox. При перетаскивании получаю следующее:
![2018-04-07_01-26-40](https://user-images.githubusercontent.com/16443248/38442785-e44a788c-3a02-11e8-9d02-7407216c90c5.png)

2018-04-06 20:34 UTC, evgenymarkov commented on public/index.js
> +HTMLElement.prototype.appendChildren = function (...children) {
JavaScript сообщество по большей степени склоняется к тому, что расширение нативных объектов - зло, я тоже такого мнения. Ты можешь найти массу холиваров на эту тему.

2018-04-09 19:14 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-10 07:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-14 07:02 UTC, evgenymarkov commented
Всё ок

2018-04-14 07:02 UTC, closed without merging