В ожидании правок
urfu-2017/webdev-task-3 pull request #35
Opened 2018-03-26 21:20 UTC by HazipovVF

2018-03-26 21:20 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-26 21:22 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-03 15:19 UTC, HazipovVF commented
ой чувствую править script.js буду
ой чувствую eventlistenerы делать надо

2018-04-03 16:47 UTC, nex2hex commented on public/script.js
> +            <img onclick="removePlace(${data.id})" class="place__img"
Вставь этот код в index.hbs, скрой через css и клонируй ноду

2018-04-05 21:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-12 15:57 UTC, nex2hex requested changes
🍅

2018-04-12 15:57 UTC, nex2hex commented on public/script.js
> +    var description = document.getElementsByClassName('main-create-place__input')[0].value;
description из пробела тоже добавится?

лучше так
`var description = document.querySelector('.main-create-place__input').value.trim();`

2018-04-12 15:57 UTC, nex2hex commented on public/script.js
> +                placeChilds[0].addEventListener("click", ()=>{removePlace(data.id)});
placeChilds[0] - плохо, завязка на html кож элемента

`placeChilds.querySelector(".button-remove").addEventListener("click", removePlace.bind(null, data.id));`

2018-04-12 15:57 UTC, nex2hex commented on public/script.js
> +        document.getElementsByClassName('main-places-header__button')[1].style.backgroundColor =
зашивать стили в код - тоже плохо
используй css классы

2018-04-12 15:57 UTC, nex2hex commented on public/script.js
> +                allPlaces[i].parentElement.style.display = 'none';
и тут

2018-04-12 15:57 UTC, nex2hex commented on public/script.js
> +    var place = document.getElementById(id);
чтобы не писать вот эту всю портянку, кажется, что можно повесить класс на родительский элемент и стили дочерних менять через css

2018-04-12 15:57 UTC, nex2hex commented on public/script.js
> +    checkboxState.id = {
что будет если сначала у одного элемента нажать изменить, а потом у второго?
`checkboxState` перезатрется значением второго и `undoChange ` работать не будет?

2018-04-17 17:43 UTC, HazipovVF commented on public/script.js
> +    checkboxState.id = {
Сколько лет программирования нужно, чтобы избегать таких ошибок?

2018-04-17 17:54 UTC, nex2hex commented on public/script.js
> +    checkboxState.id = {
такие ошибки исправляются правильной архитектурой
неплохо place завернуть в модель и навешивать биндинги внутри нее
тогда служебные переменные сами окажутся внутри модели и влиять на другие инстансы не будут

2018-04-17 17:57 UTC, nex2hex commented on public/script.js
> +    checkboxState.id = {
посмотри, например, как это сделано в todomvc
https://github.com/tastejs/todomvc/blob/gh-pages/examples/vanilla-es6/src/view.js
и http://todomvc.com/examples/vanilla-es6/

2018-04-17 18:07 UTC, HazipovVF commented on public/script.js
> +    checkboxState.id = {
я решил проще  checkboxState[id]= {}, но все же так как в примере нужно было делать мне изначально

2018-04-17 18:15 UTC, HazipovVF commented on public/script.js
> +    var place = document.getElementById(id);
place.classList.add('place_mod_edit')
захотел сделать как ты предложил и понял, что не знаю как сделать один лишь класс , который меняет стили дочерних

2018-04-17 19:40 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-18 07:44 UTC, nex2hex commented
🍏

2018-04-18 07:44 UTC, closed without merging