1
urfu-2017/webdev-task-3 pull request #7
Opened 2018-03-21 18:13 UTC by trszdev

2018-03-21 18:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-22 03:16 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-22 04:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-24 14:04 UTC, honest-hrundel commented
🍏 Пройден линтинг и базовые тесты

2018-03-24 14:14 UTC, honest-hrundel commented
🍏 Пройден линтинг и базовые тесты

2018-03-24 14:17 UTC, gogoleff commented
🍏 Пройден линтинг и базовые тесты

2018-03-24 14:17 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:17 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:17 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:17 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:17 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:17 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:17 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:17 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:17 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:17 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:17 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:17 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:18 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:29 UTC, honest-hrundel commented
🍏 Пройден линтинг и базовые тесты

2018-03-24 14:35 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:35 UTC, honest-hrundel commented
🍏 Пройден линтинг и базовые тесты

2018-03-24 14:36 UTC, honest-hrundel commented
🍏 Пройден линтинг и базовые тесты

2018-03-24 14:36 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-03-24 14:38 UTC, honest-hrundel commented
🍏 Пройден линтинг и базовые тесты

2018-03-24 14:38 UTC, honest-hrundel commented
:warning: Проверка этого решения приостановлена.<br>Подробности можно спросить у Олега Мохова (mokhov@yandex-team.ru).

2018-04-02 10:52 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-03 10:23 UTC, nex2hex requested changes
🍅

2018-04-03 10:23 UTC, nex2hex commented on public/index.css
> +    url('icofont.ttf') format('truetype'),
сейчас уже можно оcтавлять только woff (а еще лучше - woff2)
если не стоит задача поддерживать совсем старые браузеры

2018-04-03 10:23 UTC, nex2hex commented on public/utils.js
> +    if (query !== null)
лучше всегда условие в if заключать в скобки
меньше вероятность словить ошибку в дальнейшем

2018-04-03 10:23 UTC, nex2hex commented on public/utils.js
> +const ofClass = classname => {
`Array.from(document.querySelectorAll(".foo"))` ?
В большинстве случаев `Array.from` будет не нужен
https://developer.mozilla.org/ru/docs/Web/API/NodeList

2018-04-03 10:23 UTC, nex2hex commented on public/utils.js
> +    if (cls !== null)
`cls` и `classes ` два одинаковых по смыслу агрумента
сделай один и при необходимости приводи его к масииву

2018-04-03 10:23 UTC, nex2hex commented on public/utils.js
> +    if (title !== null)
`title` можно сделать частью `attrs `

2018-04-03 10:23 UTC, nex2hex commented on public/utils.js
> +        if (btnOk && e.keyCode === 13)
что такое 13? Выноси такие значения в константы, чтобы по имени было понятно, к какому символу она относится

2018-04-03 10:23 UTC, nex2hex commented on public/utils.js
> +const setSubmitButton = (node, btnOk, btnCancel) => {
что такое 13? Выноси такие значения в константы, чтобы по имени было понятно, к какому символу она относится

Функция относится к конкретной ноде, выносить ее в утилиты - неправильно
В утилитах должны быть независимые функции, например те, которые выше - вынесены сюда правильно

2018-04-03 10:23 UTC, nex2hex commented on public/utils.js
> +        if (btnOk && e.keyCode === 13)
что такое 13? Выноси такие значения в константы, чтобы по имени было понятно, к какому символу она относится

2018-04-03 10:23 UTC, nex2hex commented on public/index.js
> +        this.editButton = createElement({ name: 'button', classes: ['spot-edit', 'edit-button'], title: 'Изменить описание'  })
будет проще поддерживать и расширять код, если вынести шаблон нового элемента в html и клонировать его через https://developer.mozilla.org/ru/docs/Web/API/Node/cloneNode

2018-04-03 10:23 UTC, nex2hex commented on public/index.js
> +        if (this.prev === null)
:last-child и :first-child на элемент в списке помогут скрыть стрелочки вниз и вверх
Можно будет убрать `next` и `prev` и логика работы и вставка элемента сильно сократится

2018-04-03 10:23 UTC, nex2hex commented on public/index.js
> +        await jetch(`/api/spots/${this.current.id}/swap-with?id=${spot.id}`, 'POST')
обработку ошибок не забыл?

2018-04-03 16:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-03 17:16 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-03 17:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-03 17:17 UTC, trszdev commented on public/index.js
> +        await jetch(`/api/spots/${this.current.id}/swap-with?id=${spot.id}`, 'POST')
b8e0894

2018-04-03 17:35 UTC, trszdev commented on public/utils.js
> +const setSubmitButton = (node, btnOk, btnCancel) => {
Но там выше есть clearChild(node) ...

2018-04-03 17:35 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-03 17:37 UTC, trszdev commented on public/utils.js
> +const setSubmitButton = (node, btnOk, btnCancel) => {
setSubmitButton достаточно независима, конкретных нод там нет

2018-04-03 17:37 UTC, trszdev commented on public/utils.js
> +const setSubmitButton = (node, btnOk, btnCancel) => {
8f73156

2018-04-03 18:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-09 12:37 UTC, nex2hex commented on public/index.js
> +        await jetch(`/api/spots/${this.current.id}/swap-with?id=${spot.id}`, 'POST')
👍

2018-04-12 07:20 UTC, nex2hex requested changes
последний заход

2018-04-12 07:20 UTC, nex2hex commented on public/index.js
> +        this.editButton = createElement('.spot-edit.edit-button')
все хорошо, кроме одного момента

смотри, для создания элемента spot list item (далее - item) в списке тебе нужна разметка

сейчас ты создаешь для каждого item каждый элемент руками через кучу createElement

Приходится много писать кода, это тяжело для расширения: понимания и модификации

получается, что структура элемента списка зашита в js файл, в котором находится логика приложения и это не ок

Решение - создаем готовую html-ку item прямо внутри `<div class="node-list">`

Сейчас отрендереный код приложения с одним элементов выглядет так

```
<div class="spot-list-container">
  <ul class="spot-list">
    <li class="spot-list-item">
      <button class="spot-edit edit-button" title="Изменить описание"></button>
      <button class="spot-remove remove-button" title="Удалить место"></button>
      <input class="spot-desc-input" readonly="" value="foo">
      <button class="spot-accept accept-button hidden" title="Сохранить изменения"></button>
      <button class="spot-decline decline-button hidden" title="Отменить изменения"></button>
      <div class="spot-list-item-right">
            <button class="spot-up up-button hidden"></button>
            <button class="spot-down down-button hidden"></button>
            <input type="checkbox" title="Пометить посещенным">
      </div>
    </li>
  </ul>
</div>
```

Предлагаю index.html сделать таким
```
<div class="node-list">
      <p class="spot-list-empty">Список пуст</p>
      <ul class="spot-list">
            <li class="hidden spot-list-item spot-list-item-template">
                  <button class="spot-edit edit-button" title="Изменить описание"></button>
                  <button class="spot-remove remove-button" title="Удалить место"></button>
                  <input class="spot-desc-input" readonly="" value="foo">
                  <button class="spot-accept accept-button hidden" title="Сохранить изменения"></button>
                  <button class="spot-decline decline-button hidden" title="Отменить изменения"></button>
                  <div class="spot-list-item-right">
                        <button class="spot-up up-button hidden"></button>
                        <button class="spot-down down-button hidden"></button>
                        <input type="checkbox" title="Пометить посещенным">
                  </div>
            </li>
      </ul>
</div>      
```

В итоге js код будет примерно таким

```
const itemTemplate = document.querySelector('.spot-list-item-template')
...
constructor(...) {
      this.current = itemTemplate.cloneNode('true'); // true говорит о deep клонировании
      spotList.appendChild(this.current);

      this.current.classList.remove('hidden spot-list-item-template');

      // теперь ищем в разметки кнопки и привязываем их к переменным
      this.editButton = this.current.querySelector('.spot-edit');
      ...
      this.checkbox = this.current.querySelector('[type="checkbox"]');
      this.checkbox.checked = this.current.visited;
```

В итоге получается
 - js ничего не знает про разметку элемента, ему важно только то, что внутри есть `.spot-edit` в любом месте
 - в разметку можно добавлять любые аттрибуты, классы, другие элементы - js код модифицировать не потребуется

2018-04-15 19:43 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-16 07:56 UTC, nex2hex commented
🍏

2018-04-16 07:56 UTC, closed without merging