awd
urfu-2017/webdev-task-3 pull request #9
Opened 2018-03-21 20:54 UTC by Morkhod

2018-03-21 20:54 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-28 20:49 UTC, nex2hex commented on public/script.js
> +    [].forEach.call(places, function (place) {
`Array.from(document.getElementsByClassName()).forEach()` или `Array.prototype.forEach.call()`

2018-03-28 20:49 UTC, nex2hex commented on public/script.js
> +            .style.visibility = 'visible';
вместо управления стилями лучше менять названия классов через `classList`

2018-03-28 20:49 UTC, nex2hex commented on public/script.js
> +    const editButton = document.createElement('input');
у тебя получается очень много html кода создается в js файлах
view и логика смешиваются в одну кучу

код элементов можно было бы разместить в html в скрытых элементах и использовать https://developer.mozilla.org/ru/docs/Web/API/Node/cloneNode

2018-03-28 20:49 UTC, nex2hex commented on public/script.js
> +    deleteButton.addEventListener('click', async function () {
на каждый элемент создается своя функция со своим обработчиком

в итоге на 100 элементах у тебя будет 100 одних и тех же функций в памяти

в будущих проектах старайся использовать паттерн https://learn.javascript.ru/event-delegation

2018-03-28 20:49 UTC, nex2hex commented on public/script.js
> +            const index = storage.findIndex(_place => _place.id === place.id);
можно проще
`storage = storage.filter(_place => _place.id !== place.id);`

2018-03-29 19:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-29 20:27 UTC, nex2hex requested changes

2018-03-29 20:27 UTC, nex2hex commented on public/script.js
> +    htmlPlace.appendChild(getEditButton());
кажется, что все элементы можно объединить в один шаблон и вставлять через `htmlPlace.appendChild(getHtmlPlaceTemplate()) `

2018-03-29 20:27 UTC, nex2hex commented on public/script.js
> +    const editButton = document.querySelector('.places-item__edit-button').cloneNode(false);
Всю инициализацию ивентов можно будет перенести в одно место/функцию

```
const placeItem = ...; // ссылка на dom только что созданного элемента
const editButton = placeItem.querySelector('.places-item__edit-button');
const saveButton = placeItem.querySelector('.places-item__save-button');
...

editButton.addEventListener('click', () => {
    input.defaultValue = input.value;
    input.disabled = false;
    input.focus();
    saveButton.classList.remove('hidden');
    cancelButton.classList.remove('hidden');
});
```

2018-03-29 21:10 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-29 21:16 UTC, nex2hex reviewed
🍏

2018-03-29 21:16 UTC, nex2hex commented on public/script.js
> +        const response = await fetch(`${baseUrl}/places/${place.id}`, {
кнопка по клику не становится disabled? Т.е. можно много раз нажать и уйдет куча запросов

2018-03-29 21:16 UTC, nex2hex commented on public/script.js
> +        if (response.ok) {
если запрос был с ошибкой есть смысл добавить `else` в котором  
`saveButton.classList.remove('hidden');`

2018-03-29 21:16 UTC, nex2hex commented on public/script.js
> +        if (response.ok) {
общий код с `upButton`, кажется, что можно его вынести куда-то отсюда

2018-03-29 21:16 UTC, closed without merging